In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infecProb
0  98.522674         1   11          1           0          1
1  98.682214         1   58          0           1          0
2  98.306100         0    6          0           1          0
3  98.269797         1   85          0          -1          0
4  98.251364         1    9          0           1          0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   fever       3000 non-null   float64
 1   bodyPain    3000 non-null   int64  
 2   age         3000 non-null   int64  
 3   runnyNose   3000 non-null   int64  
 4   diffBreath  3000 non-null   int64  
 5   infecProb   3000 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 140.8 KB


In [5]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  3000.000000  3000.000000  3000.000000  3000.000000  3000.000000   
mean     99.972298     0.502333    49.693667     0.492333     0.006000   
std       1.150714     0.500078    28.774627     0.500025     0.814976   
min      98.003058     0.000000     1.000000     0.000000    -1.000000   
25%      98.978043     0.000000    25.000000     0.000000    -1.000000   
50%      99.955164     1.000000    49.000000     0.000000     0.000000   
75%     100.990006     1.000000    75.000000     1.000000     1.000000   
max     101.999833     1.000000   100.000000     1.000000     1.000000   

         infecProb  
count  3000.000000  
mean      0.496667  
std       0.500072  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [6]:
# spliting

In [7]:
import numpy as np

In [8]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]
     

In [9]:
train, test = data_split(df, 0.2)

In [10]:
train

fever  bodyPain  age  runnyNose  diffBreath  infecProb
642   101.821905         1   29          1           0          1
700    98.300147         1   47          0           0          0
226   100.859933         1   10          0          -1          1
1697   99.417789         0    4          0           0          1
1010  100.522906         0   28          0           0          0
...          ...       ...  ...        ...         ...        ...
1638   99.099132         0   61          0           1          1
1095  101.289645         1   42          1           0          1
1130  101.095697         1   33          1          -1          0
1294  101.183796         0   25          1           1          0
860   101.319741         0   43          1          -1          0

[2400 rows x 6 columns]

In [11]:
test

fever  bodyPain  age  runnyNose  diffBreath  infecProb
1801  101.430606         1   44          1           1          1
1190  100.953801         0   86          1          -1          1
1817  101.657216         1   12          0           1          1
251   101.670993         1   72          0          -1          0
2505   98.210179         0   40          0           1          1
...          ...       ...  ...        ...         ...        ...
104   101.880017         0   30          0          -1          1
2087  100.996147         1   83          0           1          1
599    98.536038         1   98          0           1          1
1756   99.689464         1   61          0          -1          0
1323  101.704867         1   46          1          -1          0

[600 rows x 6 columns]

In [12]:
X_train = train[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()
X_test = test[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [13]:
X_train

array([[101.8219045 ,   1.        ,  29.        ,   1.        ,
          0.        ],
       [ 98.30014694,   1.        ,  47.        ,   0.        ,
          0.        ],
       [100.8599334 ,   1.        ,  10.        ,   0.        ,
         -1.        ],
       ...,
       [101.095697  ,   1.        ,  33.        ,   1.        ,
         -1.        ],
       [101.1837956 ,   0.        ,  25.        ,   1.        ,
          1.        ],
       [101.3197407 ,   0.        ,  43.        ,   1.        ,
         -1.        ]])

In [14]:
X_test

array([[101.4306058 ,   1.        ,  44.        ,   1.        ,
          1.        ],
       [100.9538013 ,   0.        ,  86.        ,   1.        ,
         -1.        ],
       [101.657216  ,   1.        ,  12.        ,   0.        ,
          1.        ],
       ...,
       [ 98.53603821,   1.        ,  98.        ,   0.        ,
          1.        ],
       [ 99.68946423,   1.        ,  61.        ,   0.        ,
         -1.        ],
       [101.7048673 ,   1.        ,  46.        ,   1.        ,
         -1.        ]])

In [15]:
Y_train = train[['infecProb']].to_numpy().reshape(2400 ,)
Y_test = test[['infecProb']].to_numpy().reshape(600 ,)

In [16]:
Y_train

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [17]:
Y_test

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression()

In [20]:
inputfeatures = [101, 0, 22, -1, 1]

In [21]:
infprob = clf.predict_proba([inputfeatures])[0][1]

In [22]:
infprob

0.5252137553267364